### ISSUE TITLE
Request: Render HTML in Natural Gallery to allow links etc in titles.

### ISSUE THREAD

**Issue by SadlerJohnson** [Ecodev/natural-gallery-js#1]
Hi developers,

I would like to make a feature request for functionality that allows a user of the gallery to click on the picture to open the lightbox while a clicking on the label redirects to a link.  At present, HTML is not rendered in gallery title text, though it is in the lightbox. Bold and Italics would also be welcome but links are essential in order to link gallery images back to articles. (beta site: http://t3jer.ort.org/gallery/)

Thank you

**Comment by sambaptista** [comment]
Hello Sadler, 

Thanks for your request. Considering your demand, I've implemented the ability to insert a link to an item. Its already pubished on this repo and on packagist (natural-gallery-typo3). 

Here are some details about this implementation : Natural Gallery is most of all a **gallery**, not a rich content listing. I want it to stay simple, efficient, safe and visually consistent... but  I agree that a link is somehow a useful feature...

That's why you can now inject html inside title but be careful because I clean it :) The first injected link is used as the element link, and **all** the rest of the text is nested inside the button (and html tags are sanitized). If you inject two links, the text of the second one, will be nested inside the same button as the first link. 

About strong, italic and other styles, you can use CSS. 

_(update your theme css, there is a new instruction to style the button)._ 

Update your library, have a try, and don't hesitate to give feedback.

Best regards.
