### ISSUE TITLE
[Feature] Events on collection set and e.t.c

### ISSUE THREAD

**Issue by Tsyklop** [Ecodev/natural-gallery-js#17]
Can you make event after collection is set? or added new items

**Comment by sambaptista** [comment]
Just to be sure, you want the gallery to emits a notification when it's collection has just change ?

Can you provide usecase plz.

**Comment by sambaptista** [comment]
v4 is coming and there will be some events :

* pagination : required items to populate the gallery
* activate : notifies item link or item button has been clicked
* zoom : photoswipe has open -> provides photoswipe object, with all it's options and specific events
* select : notifies the list of selected items (by checkbox).
* item added to DOM from buffer (name to be defined)
* item became visible

There already is some actually, but they are not consistent and have been deployed fast for a project. It's better to wait for v4 that is coming for end of month.

In your case you set a collection (or add items) to the gallery and wants the gallery to notify you that the collection has been setted or items added. The gallery will not emit that kind of events because, as a developper, you already know when you affect the collection. The gallery will notify interactions made by the end user. 

A more consistent docs are coming too. V4 will be a major release with lots of changes in public api.

I close request for now. If you can provide a **good** usecase where you can add items to the gallery without beeing able to do your callback functions, I can reconsider your request and you can re-open it.
