### ISSUE TITLE
Prevent narrow images to be covered by button

### ISSUE THREAD

**Issue by sambaptista** [Ecodev/natural-gallery-js#21]
Narrow images combined with large button label, could have a relatively bad rendering :

![46474368-f4e53b00-c7e2-11e8-81fb-cc0991f7fc3e](https://user-images.githubusercontent.com/5111137/46476957-b56e1d00-c7e9-11e8-9d0c-e0e763c46244.jpg)

An option to limit format disproportion would be nice as well in natural and masonry format.

Easiest solutions : 
- add minWidth option in natural format.
- add maxHeight option in masonry format.

Half hard, half easy : 
- add ratio restriction option (in masonry and natural format) -> maybe better solution ?

Hardest solutions : 
- limit number of label rows (if all the button text isn't important)
- limit the percentage of the image area that is covered by the button -> inapplicable ? not predictable before rendering.

**Comment by PowerKiKi** [comment]
I observed some issues which are closely related to this too.

The attached zip contains 4 images with extreme ratios and illustrate that some images will "disappear" with certain window sizes. To reproduce you can upload images in Dilps, (in the reverse order, so they appear in the correct order), then refresh the home page, and resize the window.

You might as well observe that after resizing the window, the layout will somehow "animate" and grow/shrink a few pixels at a time until it reaches a fitting size. Refreshing the whole page will skip this undesired animation.

The ratio part really is extreme and it might be acceptable to do nothing at all. But maybe having a minimal width could be an easy fix if it also help for button label ?

The animation thing might be more annoying, because if looks like the whole app is slowing down and not showing any images for a few seconds (or blinking images)..

![image](https://user-images.githubusercontent.com/72603/46512280-5ca88e00-c896-11e8-88bd-780a9ec43c1a.png)

![image](https://user-images.githubusercontent.com/72603/46512284-5fa37e80-c896-11e8-94d8-444e49e0aff5.png)




[extreme ratios.zip](https://github.com/Ecodev/natural-gallery-js/files/2448701/extreme.ratios.zip)

**Comment by sambaptista** [comment]
I've implemented an option to limit the ratio :

```js
 var options = {
        rowHeight: 400,
        ratioLimit: {
            min: 0.5,
            max: 2
        }
    };
```

It's the more generic to control vertical and narrows images, in both Natural and Masonry format.

Using min = 1 and max = 1 force square. Using this option on  Natural format results in the same result as  ResponsiveSquare format. It becomes obsolete and will be removed. 

Will be published with next release v6.
