### ISSUE TITLE
Is the category part all gone since v4?

### ISSUE THREAD

**Issue by nielsrune** [Ecodev/natural-gallery-js#25]
I have just manages to update to the new v4 gallery. Great work!

I really liked the category option from the old version. Is it all gone, or will it be reimplemented in the future?

**Comment by sambaptista** [comment]
Hello. Thanks :)

On the first versions of this lib, the header was built for specific needs on a project where category filtering was required.

With next improvements, I've decided to remove all header features because searching has too much diversity and is impossible to achieve correctly. This must be "outsourced" and won't come back in this lib that is now only focused on rendering images and do it well. 

But ...

We have started this angular searchbar component https://github.com/Ecodev/natural-search. With the incoming feature Angular Elements we can hope to use it out of angular projects one day. This is only a filter set builder... we still need to build a javascript search engine to filter a list of elements.The filtered result could then be sent to natural-gallery-js for rendering... 

Wait and see...
