### ISSUE TITLE
[feature] Download Button for Images

### ISSUE THREAD

**Issue by unix0r** [Ecodev/natural-gallery-js#34]
What about a button for downloading images?

I would like to use the natural gallery to share some photos with friends and want them to be able to download pictures they like.

**Comment by sambaptista** [comment]
Hi,

I never thought about a download action before. After thinking more deeply about it, I'm unsure about the way this should be done.

Do you have specific usecase about how to achieve this action ?

**Comment by unix0r** [comment]
Well, i'm not a web developer, but we have the path to the image for showing it in the gallery, so why should'nt we just pass the link to the browser for downloading?

**Comment by sambaptista** [comment]
The url is not enough for generic usecase.

As you're not web developper, I don't enter in details, but there are many interpretations of what a download action could be, and what is downloaded content (bulk, size, format, compression). Most of those actions must be achieved by the server and are specific to each project needs and usecase (that's why I asked you some usecase...)

This library is mostly browser side only and can't achieve most of download tasks. I can suggest you to use the native right click + save image as on enlarged version. I would be counter productive to develop a shortcut for a so basic and native feature.
