### ISSUE TITLE
Getting started guide does not include requisite markup

### ISSUE THREAD

**Issue by adcdr** [Ecodev/natural-gallery-js#43]
When I followed the [getting started guide](https://ecodev.github.io/natural-gallery-js/docs-getting-started.html) I was unable to get infinite scroll working. 
Eventually, I figured out that there is some expected placeholder markup that is not mentioned in the guide.

I raised a PR on a fork containing an update that would be helpful for new users: https://github.com/Ecodev/natural-gallery-js/pull/42

**Comment by sambaptista** [comment]
Hello ! Thank you for your feedback and pull request. 

I will have a deeper look on it. The additionnal styling you added `overflow:auto; min-height:100%; height:100%;` should not be required. Do you have an example (without that styling) where infinite scroll doesn't work ? 

Maybe I need to fix something on the lib rather than complete the docs with a workaround.

**Comment by sambaptista** [comment]
Oh I think I have a point. 

When you instantiate a gallery you can provide the scrollable element ref : 

```js
new NaturalGallery(destinationRef, options, photoswipeRef, scrollableRef);
```

When scrollableRef is not provided, the gallery fallbacks on the body element. I think you have another div that is taking the overflow and the lib is not aware of that. The styles you added give the management of the overflow back to the body and the infinite scroll starts to work again.

I will add complete the docs and fix the typos you've suggested in your pull request. Thanks. 

Keep me informed if that makes sense in your use case.

**Comment by adcdr** [comment]
Hello,

Thanks for getting back to me.

I did some investigation and created a minimal example here:
https://gist.github.com/adcdr/6c1c3ceecaab47ac1905a9a9f184ab83#file-natural-gallery-example-html

I tried setting the scrollable element in 4 different ways:

1. document.getElementById('body');
2. document
3. document.body
4. window

The only option that seems to work is 1. I added some comments in the Gist linked above with reasons for why the other options do not work.

By the way, the default scrollable element is set to  _document_, as seen [here](https://github.com/Ecodev/natural-gallery-js/blob/5644c50e15a188447d3a479372fbd2ae52e68f6e/src/js/galleries/AbstractGallery.ts#L302). But using either _document_ or _document.body_ does not work.

Since you mentioned that the library is supposed to work without any boilerplate markup, then I think you could use the _window_ object as the fallback scrollable elment as it is scrollable by default.
However the _scroll_ callback will need updating too for this option. 

I have added some more information in the Gist comments.

**Comment by sambaptista** [comment]
Your example confirms what I've said in my last post.

You give to your div#body the ability to scroll by css  with your instruction `overflow:auto; height:100%...`. This becomes the scrollable element inside which the gallery can "grow". 

That means the document/windows don't scroll anymore. This is div#body that "captures" the scrolls and you have to tell it to the gallery, otherwise, it will listen to events on window that will never occur.

You have to instantiate the gallery this way : 

```js
 gallery = getGallery(galleryElement, undefined, document.getElementById('body'));
```

The alternative is to prevent any non-root html element that wraps the gallery to be scrollable. This way the scrollable element will become the Window element, and the gallery could be instantiated without additional reference :

```js
 gallery = getGallery(galleryElement);
```

Everything seems to be working as intented.

> then I think you could use the window object as the fallback scrollable elment as it is scrollable by default.

I do exactly that for exactly this reason. But if you give management of the overflow to another DIV, the window has no more overflow to manage ;)

I hope this helps. I close the ticket but feel free to re-open if needed.

**Comment by adcdr** [comment]
As far as I can tell you don't use `window` as the default scrollable item, you use `document`:
```
this.bindScroll(this.scrollElementRef || document);
```
[[link to source]](https://github.com/Ecodev/natural-gallery-js/blob/5644c50e15a188447d3a479372fbd2ae52e68f6e/src/js/galleries/AbstractGallery.ts#L302)

Perhaps I am misunderstanding, and if you can provide a minimal example where it works with the following that would help clear the confusion.
```
gallery = getGallery(galleryElement);
```

Anyway this is not causing me any problems as I have a workaround. Just wanted to make you aware.

**Comment by sambaptista** [comment]
Ok I get what you mean and I pointed where is issue is exactly coming from.

The heart of the problem here is it not the scroll detection itself, it's the viewport height computing. The gallery is designed to show images to fill the viewport until there is an overflow. Then it starts to listen to scroll events. Using `document` is ok for that because it's the root of the DOM (`window` is just an object apart from the DOM).

I should use the viewport to tell the gallery the minimum height to fill with images, but I don't. `getGalleryVisibleHeight()` uses `document` and should be using `window`. Document can be too small if nothing is done on developper side. By default it equals 0. In those conditions, the gallery think the viewport is 0 pixel height and doesn't extend enough to create an overflow.

With your exemple you fixed it the same way I did in the demo with height:100%. 

I'll definitely fix it. Thanks for your carefullness.
