### ISSUE TITLE
no documented way to stop infinite scroll if no images are returned

### ISSUE THREAD

**Issue by rpaditya** [Ecodev/natural-gallery-js#45]
There might be a way to do this already, but I can't seem to find an effective one, but I have infinite scrolling/loading working but at some point some searches don't return any more images -- I can do this:

if (items.length > 0){
                    gallery.addItems(items);
                }

but this doesn't stop trying to get the image list from the remote url if the user keeps trying to scroll...is there a good way to stop scroll detection if we get back 0 items?

**Comment by sambaptista** [comment]
Good point.

Usually a long gallery doesn't have much space bellow, and there is no more scroll event if users is already on the bottom of page. I guess under your gallery you have more content ?

**Comment by rpaditya** [comment]
I am just following what is in the demo -- the bottom of my gallery/page is the same as you have in the demo:
<div class="row">
    <div class="container-90perc">
        <div id="gallery"></div>
    </div>
</div>

**Comment by rpaditya** [comment]
`<div class="row">
    <div class="container-90perc">
        <div id="gallery"></div>
    </div>
</div>`

**Comment by rpaditya** [comment]
a div of class "container-90perc"

**Comment by sambaptista** [comment]
Ok it's normal, and there is no way to stop it (but I think about it). 

The reason is that the buffer continues to ask images as long as you keep displaying items into the DOM. There is no way to know the list is over, but when there is nothing more to display, there is nothing more to ask either.

That means, there could be a few queries that return no result, but it's by design, nothing dysfonctionnal.
