### ISSUE TITLE
Can't get automatic loading to work

### ISSUE THREAD

**Issue by plouj** [Ecodev/natural-gallery-js#5]
I can't figure out why my relatively simple gallery isn't loading automatically when I scroll to the bottom of the page. Most of the code should be close to identical to the [first demo](https://ecodev.ch/natural-gallery/demo/). You can find the code [here](https://gist.github.com/plouj/d545a878798da232de25d2fc285a3794)

Here's a screenshot:
![scroll-blocked](https://user-images.githubusercontent.com/282428/32139362-1ac3140e-bc14-11e7-8bf5-b435de356b71.png)

**Comment by sambaptista** [comment]
Hi !

It's because of [this line](https://github.com/Ecodev/natural-gallery-js/blob/99fbd6cdac6dca0c6f925cd4baefa611d2bce668/app/js/Controller.ts#L91) that requires 60px of free space after gallery to add new "page". 

This padding is in the CSS in my demo. In your's, you can just add <style>body { padding-bottom:60px} </style> to enable infinite scroll. 

Could be a setting... maybe...

**Comment by plouj** [comment]
I don't quite understand the math on this one, but is it possible for the code to automatically detect the amount of space based on the given element's padding? Does it have to be a non-zero value?

**Comment by sambaptista** [comment]
There is no mathematical reason to have 60px margin. Its to prevent the autoload to fire too fast, and be invisible. 

You can set margin-bottom on the gallery element instead of padding in the body, this will do the same effect. It works without padding at all if you have more content after gallery.

**Comment by sambaptista** [comment]
I re-open to add an option to allow the user to configure this offset.

**Comment by sambaptista** [comment]
The option has been added.
