### ISSUE TITLE
gallery.removeEventListener

### ISSUE THREAD

**Issue by johtso** [Ecodev/natural-gallery-js#82]
There should probably be a `removeEventListener` function. Currently I have a listener that I only want to fire the first time the event happens (after the first image has loaded). It would be nice to be able to clean up after myself.

**Comment by PowerKiKi** [comment]
Instead of `removeEventListener`, I'd recommend exposing the underlying [options](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#parameters) as seen below. That gives the possibility to use `once`, or `signal` which is the superior way to remove an event listener nowadays. 

```diff
- public addEventListener(name: [...], callback: [...]): void {
-     this.elementRef.addEventListener(name, callback);
+ public addEventListener(name: [...], callback: [...], options?: AddEventListenerOptions): void {
+     this.elementRef.addEventListener(name, callback, options);
```

**Comment by johtso** [comment]
@PowerKiKi even better! Thanks, I didn't know you could do all those things with options.
